# Generated by Django 2.2 on 2020-08-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('phone', models.CharField(max_length=10, verbose_name='телефон')),
                ('adres', models.CharField(max_length=100, verbose_name='адрес')),
                ('data', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('products', models.ManyToManyField(related_name='продукты', to='webapp.Product')),
            ],
        ),
    ]
